<?php

/**
 * Premium Layout System — 8 hand-crafted Elementor layouts.
 * Each layout is a complete design system with CSS, JS, header, footer, and 5 pages.
 */
return [
    'noir' => [
        'class' => \App\Services\Layouts\LayoutNoir::class,
        'name' => 'Noir',
        'style' => 'dark',
        'primary' => '#FF4500',
        'accent' => '#FFB800',
        'preview_bg' => '#080808',
        'best_for' => ['Sports', 'Fitness', 'Tech', 'Auto', 'Agency'],
        'keywords' => ['gym', 'fitness', 'sports', 'training', 'automotive', 'car', 'tech', 'agency', 'gaming', 'esports', 'basketball', 'football', 'boxing', 'martial arts', 'crossfit'],
    ],
    'ivory' => [
        'class' => \App\Services\Layouts\LayoutIvory::class,
        'name' => 'Ivory',
        'style' => 'light',
        'primary' => '#1B4D3E',
        'accent' => '#D4A574',
        'preview_bg' => '#FAFAF8',
        'best_for' => ['Medical', 'Legal', 'Finance', 'Education'],
        'keywords' => ['medical', 'doctor', 'clinic', 'hospital', 'dental', 'law', 'legal', 'attorney', 'lawyer', 'finance', 'accounting', 'bank', 'insurance', 'education', 'school', 'university', 'tutoring', 'consulting'],
    ],
    'azure' => [
        'class' => \App\Services\Layouts\LayoutAzure::class,
        'name' => 'Azure',
        'style' => 'modern',
        'primary' => '#2563EB',
        'accent' => '#06B6D4',
        'preview_bg' => '#F8FAFC',
        'best_for' => ['SaaS', 'Tech', 'Agency', 'Startup'],
        'keywords' => ['saas', 'software', 'app', 'startup', 'digital', 'marketing', 'seo', 'web design', 'it', 'technology', 'cloud', 'ai', 'data', 'analytics'],
    ],
    'blush' => [
        'class' => \App\Services\Layouts\LayoutBlush::class,
        'name' => 'Blush',
        'style' => 'elegant',
        'primary' => '#C9A87C',
        'accent' => '#D4A574',
        'preview_bg' => '#FBF9F7',
        'best_for' => ['Beauty', 'Wedding', 'Spa', 'Fashion'],
        'keywords' => ['beauty', 'salon', 'spa', 'wedding', 'event', 'planner', 'fashion', 'boutique', 'cosmetics', 'hair', 'nail', 'skincare', 'makeup', 'florist', 'bakery'],
    ],
    'ember' => [
        'class' => \App\Services\Layouts\LayoutEmber::class,
        'name' => 'Ember',
        'style' => 'dark',
        'primary' => '#DC2626',
        'accent' => '#F59E0B',
        'preview_bg' => '#0C0A09',
        'best_for' => ['Restaurant', 'Food', 'Entertainment', 'Nightlife'],
        'keywords' => ['restaurant', 'food', 'cafe', 'bar', 'pizza', 'sushi', 'catering', 'chef', 'entertainment', 'nightclub', 'music', 'dj', 'event venue', 'brewery'],
    ],
    'forest' => [
        'class' => \App\Services\Layouts\LayoutForest::class,
        'name' => 'Forest',
        'style' => 'light',
        'primary' => '#2D6A4F',
        'accent' => '#95D5B2',
        'preview_bg' => '#FAFAF5',
        'best_for' => ['Real Estate', 'Construction', 'Home Services', 'Landscaping'],
        'keywords' => ['real estate', 'property', 'construction', 'contractor', 'plumbing', 'electrical', 'hvac', 'roofing', 'landscaping', 'cleaning', 'moving', 'handyman', 'pest control', 'painting'],
    ],
    'slate' => [
        'class' => \App\Services\Layouts\LayoutSlate::class,
        'name' => 'Slate',
        'style' => 'minimal',
        'primary' => '#334155',
        'accent' => '#94A3B8',
        'preview_bg' => '#FAFAFA',
        'best_for' => ['Portfolio', 'Photography', 'Creative', 'Architecture'],
        'keywords' => ['portfolio', 'photography', 'photographer', 'creative', 'design', 'architect', 'architecture', 'interior design', 'art', 'gallery', 'studio', 'freelance', 'graphic design'],
    ],
    'royal' => [
        'class' => \App\Services\Layouts\LayoutRoyal::class,
        'name' => 'Royal',
        'style' => 'dark',
        'primary' => '#7C3AED',
        'accent' => '#A78BFA',
        'preview_bg' => '#0C0A1A',
        'best_for' => ['Hospitality', 'Hotel', 'Luxury Retail', 'Jewelry'],
        'keywords' => ['hotel', 'resort', 'luxury', 'jewelry', 'watch', 'wine', 'concierge', 'vip', 'premium', 'exclusive', 'travel', 'cruise', 'limousine', 'yacht'],
    ],
    'biddut' => [
        'class' => \App\Services\Layouts\LayoutBiddut::class,
        'name' => 'Biddut',
        'style' => 'professional',
        'primary' => '#007FFF',
        'accent' => '#3E976C',
        'preview_bg' => '#0A0F2C',
        'theme_based' => true,
        'theme_slug' => 'biddut',
        'best_for' => ['Electrical Services', 'Contractors', 'Home Services', 'Industrial'],
        'keywords' => ['electric', 'electrical', 'electrician', 'wiring', 'power', 'voltage', 'circuit', 'panel', 'generator', 'solar', 'energy', 'utility', 'service', 'services', 'contractor', 'maintenance', 'repair', 'installation', 'industrial', 'commercial services', 'home services', 'ac repair', 'heating', 'cooling', 'appliance'],
    ],
];
