// WebNewBiz Figma Plugin — Main Logic (runs in Figma sandbox)

figma.showUI(__html__, { width: 400, height: 600, themeColors: true });

figma.ui.onmessage = async (msg: { type: string; data?: unknown }) => {
  switch (msg.type) {
    case 'generate-design':
      await handleGenerateDesign(msg.data as { prompt: string; style: string });
      break;
    case 'image-to-design':
      await handleImageToDesign(msg.data as { imageBytes: Uint8Array });
      break;
    case 'export-to-code':
      await handleExportToCode(msg.data as { outputType: string });
      break;
    case 'cancel':
      figma.closePlugin();
      break;
  }
};

async function handleGenerateDesign(data: { prompt: string; style: string }) {
  figma.ui.postMessage({ type: 'status', message: 'Generating design...' });

  // Create a frame for the design
  const frame = figma.createFrame();
  frame.name = 'AI Generated Design';
  frame.resize(1440, 900);
  frame.fills = [{ type: 'SOLID', color: { r: 0.04, g: 0.04, b: 0.06 } }];

  // Hero section
  const hero = figma.createFrame();
  hero.name = 'Hero Section';
  hero.resize(1440, 600);
  hero.fills = [{ type: 'SOLID', color: { r: 0.05, g: 0.1, b: 0.2 } }];
  frame.appendChild(hero);

  // Title text
  const title = figma.createText();
  await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });
  title.fontName = { family: 'Inter', style: 'Bold' };
  title.characters = data.prompt.substring(0, 50) || 'Your Website Title';
  title.fontSize = 64;
  title.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
  title.x = 120;
  title.y = 200;
  hero.appendChild(title);

  // Subtitle
  const subtitle = figma.createText();
  await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
  subtitle.fontName = { family: 'Inter', style: 'Regular' };
  subtitle.characters = 'AI-powered design generated by WebNewBiz';
  subtitle.fontSize = 20;
  subtitle.fills = [{ type: 'SOLID', color: { r: 0.6, g: 0.6, b: 0.7 } }];
  subtitle.x = 120;
  subtitle.y = 290;
  hero.appendChild(subtitle);

  // CTA Button
  const btn = figma.createRectangle();
  btn.name = 'CTA Button';
  btn.resize(200, 56);
  btn.cornerRadius = 12;
  btn.fills = [{ type: 'SOLID', color: { r: 0.23, g: 0.51, b: 0.96 } }];
  btn.x = 120;
  btn.y = 350;
  hero.appendChild(btn);

  const btnText = figma.createText();
  btnText.fontName = { family: 'Inter', style: 'Bold' };
  btnText.characters = 'Get Started';
  btnText.fontSize = 16;
  btnText.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
  btnText.x = 155;
  btnText.y = 368;
  hero.appendChild(btnText);

  figma.currentPage.appendChild(frame);
  figma.viewport.scrollAndZoomIntoView([frame]);

  figma.ui.postMessage({ type: 'done', message: 'Design generated!' });
}

async function handleImageToDesign(data: { imageBytes: Uint8Array }) {
  figma.ui.postMessage({ type: 'status', message: 'Analyzing image...' });

  // Create image from bytes
  const image = figma.createImage(data.imageBytes);
  const frame = figma.createFrame();
  frame.name = 'Image to Design';
  frame.resize(1440, 900);
  frame.fills = [{ type: 'IMAGE', imageHash: image.hash, scaleMode: 'FILL' }];

  figma.currentPage.appendChild(frame);
  figma.viewport.scrollAndZoomIntoView([frame]);

  figma.ui.postMessage({ type: 'done', message: 'Image imported! Layers will be created by AI.' });
}

async function handleExportToCode(data: { outputType: string }) {
  const selection = figma.currentPage.selection;
  if (selection.length === 0) {
    figma.ui.postMessage({ type: 'error', message: 'Please select a frame to export.' });
    return;
  }

  const node = selection[0];
  figma.ui.postMessage({ type: 'status', message: `Exporting ${node.name} as ${data.outputType}...` });

  // Collect node data for API
  const nodeData = {
    name: node.name,
    type: node.type,
    width: 'width' in node ? node.width : 0,
    height: 'height' in node ? node.height : 0,
  };

  figma.ui.postMessage({
    type: 'export-data',
    data: { node: nodeData, outputType: data.outputType },
  });
}
