<?php

return [
    'name' => env('APP_NAME', 'Webnewbiz'),
    'domain' => env('PLATFORM_DOMAIN', 'webnewbiz.com'),
    'subdomain_suffix' => env('PLATFORM_SUBDOMAIN_SUFFIX', '.webnewbiz.com'),

    'defaults' => [
        'wordpress_version' => 'latest',
        'php_version' => env('CLOUDPANEL_DEFAULT_PHP', '8.2'),
        'elementor_version' => 'latest',
    ],

    'limits' => [
        'free' => ['websites' => 1, 'storage_gb' => 1, 'bandwidth_gb' => 10],
        'starter' => ['websites' => 5, 'storage_gb' => 10, 'bandwidth_gb' => 100],
        'business' => ['websites' => 20, 'storage_gb' => 50, 'bandwidth_gb' => 500],
        'agency' => ['websites' => 100, 'storage_gb' => 200, 'bandwidth_gb' => 2000],
    ],

    'backup' => [
        'retention_days' => 30,
        'max_backups_per_site' => 10,
        'storage_path' => storage_path('app/backups'),
    ],

    'screenshot' => [
        'storage_path' => storage_path('app/screenshots'),
        'width' => 1280,
        'height' => 800,
    ],

    // Envato master theme sites (for clone-based provisioning)
    'envato_masters' => [
        'barab' => [
            'path' => 'C:/xampp/htdocs/master-barab',
            'db' => 'wp_master_barab',
            'demo_domain' => 'https://wordpress.themehour.net/barab',
            'theme_slug' => 'barab',
            'theme_source' => 'envato-themes/barab-extracted/barab',
            'demo_xml' => 'envato-themes/barab-extracted/barab/inc/demo-data/barab-demo.xml',
            'demo_options' => 'envato-themes/barab-extracted/barab/inc/demo-data/redux_options_demo.json',
            'options_format' => 'redux_json',
            'required_plugins' => ['barab-core', 'elementor', 'contact-form-7', 'redux-framework', 'cmb2'],
            'companion_plugin' => [
                'slug' => 'barab-core',
                'source' => 'envato-themes/barab/barab-core.zip',
            ],
            'label' => 'Restaurant & Food',
            'best_for' => 'restaurants, cafes, bakeries, food businesses, bars, catering',
        ],
        'geoport' => [
            'path' => 'C:/xampp/htdocs/master-geoport',
            'db' => 'wp_master_geoport',
            'demo_domain' => 'https://pluginspoint.com/geoport',
            'theme_slug' => 'geoport',
            'theme_source' => 'envato-themes/geoport-extracted/geoport',
            'demo_xml' => 'envato-themes/geoport-extracted/geoport/inc/plugins/geoport-master/demo-importer/demo/demo-content.xml',
            'demo_options' => 'envato-themes/geoport-extracted/geoport/inc/plugins/geoport-master/demo-importer/demo/options.txt',
            'options_format' => 'codestar_serialized',
            'required_plugins' => ['geoport-master', 'elementor', 'contact-form-7', 'redux-framework', 'cmb2'],
            'companion_plugin' => [
                'slug' => 'geoport-master',
                'source_dir' => 'envato-themes/geoport-extracted/geoport/inc/plugins/geoport-master',
            ],
            'label' => 'Agency & General Business',
            'best_for' => 'agencies, consulting, corporate, general business, professional services',
        ],
        'transland' => [
            'path' => 'C:/xampp/htdocs/master-transland',
            'db' => 'wp_master_transland',
            'demo_domain' => 'https://modinatheme.com/transland',
            'theme_slug' => 'transland',
            'theme_source' => 'envato-themes/transland-extracted/transland',
            'demo_xml' => 'envato-themes/transland-extracted/transland/inc/demo/contents.xml',
            'demo_options' => 'envato-themes/transland-extracted/transland/inc/demo/settings.json',
            'options_format' => 'redux_json',
            'required_plugins' => ['modina-core', 'elementor', 'contact-form-7', 'redux-framework', 'cmb2'],
            'companion_plugin' => [
                'slug' => 'modina-core',
                'source' => 'envato-themes/transland-extracted/transland/inc/tgm/plugins/modina-core.zip',
            ],
            'label' => 'Transport & Industrial',
            'best_for' => 'trucking, logistics, construction, manufacturing, industrial services',
        ],

        // ── New Envato themes (placeholders — update paths after purchase) ──

        'flavor-medical' => [
            'path' => 'C:/xampp/htdocs/master-flavor-medical',
            'db' => 'wp_master_flavor_medical',
            'demo_domain' => '',
            'theme_slug' => 'flavor-medical',
            'theme_source' => 'envato-themes/flavor-medical-extracted/flavor-medical',
            'demo_xml' => 'envato-themes/flavor-medical-extracted/flavor-medical/demo/content.xml',
            'demo_options' => 'envato-themes/flavor-medical-extracted/flavor-medical/demo/options.json',
            'options_format' => 'redux_json',
            'required_plugins' => ['elementor', 'contact-form-7'],
            'companion_plugin' => ['slug' => 'flavor-medical-core', 'source' => 'envato-themes/flavor-medical/companion.zip'],
            'label' => 'Medical & Healthcare',
            'best_for' => 'clinics, doctors, hospitals, dental, pharmacy, medical practices, therapists',
        ],
        'flavor-law' => [
            'path' => 'C:/xampp/htdocs/master-flavor-law',
            'db' => 'wp_master_flavor_law',
            'demo_domain' => '',
            'theme_slug' => 'flavor-law',
            'theme_source' => 'envato-themes/flavor-law-extracted/flavor-law',
            'demo_xml' => 'envato-themes/flavor-law-extracted/flavor-law/demo/content.xml',
            'demo_options' => 'envato-themes/flavor-law-extracted/flavor-law/demo/options.json',
            'options_format' => 'redux_json',
            'required_plugins' => ['elementor', 'contact-form-7'],
            'companion_plugin' => ['slug' => 'flavor-law-core', 'source' => 'envato-themes/flavor-law/companion.zip'],
            'label' => 'Law & Legal',
            'best_for' => 'lawyers, attorneys, law firms, legal services, notary, solicitors',
        ],
        'flavor-beauty' => [
            'path' => 'C:/xampp/htdocs/master-flavor-beauty',
            'db' => 'wp_master_flavor_beauty',
            'demo_domain' => '',
            'theme_slug' => 'flavor-beauty',
            'theme_source' => 'envato-themes/flavor-beauty-extracted/flavor-beauty',
            'demo_xml' => 'envato-themes/flavor-beauty-extracted/flavor-beauty/demo/content.xml',
            'demo_options' => 'envato-themes/flavor-beauty-extracted/flavor-beauty/demo/options.json',
            'options_format' => 'redux_json',
            'required_plugins' => ['elementor', 'contact-form-7'],
            'companion_plugin' => ['slug' => 'flavor-beauty-core', 'source' => 'envato-themes/flavor-beauty/companion.zip'],
            'label' => 'Beauty & Salon',
            'best_for' => 'salons, beauty, spa, hair, nails, barber, makeup, skincare',
        ],
        'flavor-realestate' => [
            'path' => 'C:/xampp/htdocs/master-flavor-realestate',
            'db' => 'wp_master_flavor_realestate',
            'demo_domain' => '',
            'theme_slug' => 'flavor-realestate',
            'theme_source' => 'envato-themes/flavor-realestate-extracted/flavor-realestate',
            'demo_xml' => 'envato-themes/flavor-realestate-extracted/flavor-realestate/demo/content.xml',
            'demo_options' => 'envato-themes/flavor-realestate-extracted/flavor-realestate/demo/options.json',
            'options_format' => 'redux_json',
            'required_plugins' => ['elementor', 'contact-form-7'],
            'companion_plugin' => ['slug' => 'flavor-realestate-core', 'source' => 'envato-themes/flavor-realestate/companion.zip'],
            'label' => 'Real Estate',
            'best_for' => 'real estate, property, realtor, housing, apartments, rentals, brokers',
        ],
        'flavor-education' => [
            'path' => 'C:/xampp/htdocs/master-flavor-education',
            'db' => 'wp_master_flavor_education',
            'demo_domain' => '',
            'theme_slug' => 'flavor-education',
            'theme_source' => 'envato-themes/flavor-education-extracted/flavor-education',
            'demo_xml' => 'envato-themes/flavor-education-extracted/flavor-education/demo/content.xml',
            'demo_options' => 'envato-themes/flavor-education-extracted/flavor-education/demo/options.json',
            'options_format' => 'redux_json',
            'required_plugins' => ['elementor', 'contact-form-7'],
            'companion_plugin' => ['slug' => 'flavor-education-core', 'source' => 'envato-themes/flavor-education/companion.zip'],
            'label' => 'Education & School',
            'best_for' => 'schools, universities, tutors, academies, courses, online learning, training',
        ],
        'flavor-fitness' => [
            'path' => 'C:/xampp/htdocs/master-flavor-fitness',
            'db' => 'wp_master_flavor_fitness',
            'demo_domain' => '',
            'theme_slug' => 'flavor-fitness',
            'theme_source' => 'envato-themes/flavor-fitness-extracted/flavor-fitness',
            'demo_xml' => 'envato-themes/flavor-fitness-extracted/flavor-fitness/demo/content.xml',
            'demo_options' => 'envato-themes/flavor-fitness-extracted/flavor-fitness/demo/options.json',
            'options_format' => 'redux_json',
            'required_plugins' => ['elementor', 'contact-form-7'],
            'companion_plugin' => ['slug' => 'flavor-fitness-core', 'source' => 'envato-themes/flavor-fitness/companion.zip'],
            'label' => 'Fitness & Gym',
            'best_for' => 'gyms, fitness, trainers, yoga, crossfit, workout, martial arts, sports',
        ],
        'flavor-tech' => [
            'path' => 'C:/xampp/htdocs/master-flavor-tech',
            'db' => 'wp_master_flavor_tech',
            'demo_domain' => '',
            'theme_slug' => 'flavor-tech',
            'theme_source' => 'envato-themes/flavor-tech-extracted/flavor-tech',
            'demo_xml' => 'envato-themes/flavor-tech-extracted/flavor-tech/demo/content.xml',
            'demo_options' => 'envato-themes/flavor-tech-extracted/flavor-tech/demo/options.json',
            'options_format' => 'redux_json',
            'required_plugins' => ['elementor', 'contact-form-7'],
            'companion_plugin' => ['slug' => 'flavor-tech-core', 'source' => 'envato-themes/flavor-tech/companion.zip'],
            'label' => 'Tech & SaaS',
            'best_for' => 'technology, software, SaaS, IT, apps, startups, digital, cloud, AI',
        ],
        'flavor-hotel' => [
            'path' => 'C:/xampp/htdocs/master-flavor-hotel',
            'db' => 'wp_master_flavor_hotel',
            'demo_domain' => '',
            'theme_slug' => 'flavor-hotel',
            'theme_source' => 'envato-themes/flavor-hotel-extracted/flavor-hotel',
            'demo_xml' => 'envato-themes/flavor-hotel-extracted/flavor-hotel/demo/content.xml',
            'demo_options' => 'envato-themes/flavor-hotel-extracted/flavor-hotel/demo/options.json',
            'options_format' => 'redux_json',
            'required_plugins' => ['elementor', 'contact-form-7'],
            'companion_plugin' => ['slug' => 'flavor-hotel-core', 'source' => 'envato-themes/flavor-hotel/companion.zip'],
            'label' => 'Hotel & Hospitality',
            'best_for' => 'hotels, resorts, booking, travel, lodges, hospitality, tourism, vacation',
        ],
        'flavor-shop' => [
            'path' => 'C:/xampp/htdocs/master-flavor-shop',
            'db' => 'wp_master_flavor_shop',
            'demo_domain' => '',
            'theme_slug' => 'flavor-shop',
            'theme_source' => 'envato-themes/flavor-shop-extracted/flavor-shop',
            'demo_xml' => 'envato-themes/flavor-shop-extracted/flavor-shop/demo/content.xml',
            'demo_options' => 'envato-themes/flavor-shop-extracted/flavor-shop/demo/options.json',
            'options_format' => 'redux_json',
            'required_plugins' => ['elementor', 'contact-form-7', 'woocommerce'],
            'companion_plugin' => ['slug' => 'flavor-shop-core', 'source' => 'envato-themes/flavor-shop/companion.zip'],
            'label' => 'eCommerce & Shop',
            'best_for' => 'shops, stores, ecommerce, retail, fashion, boutiques, online marketplace',
        ],
    ],

    // XAMPP local development settings
    'xampp_htdocs' => env('XAMPP_HTDOCS', 'C:/xampp/htdocs'),
    'wp_base_path' => env('WP_BASE_PATH', 'C:/xampp/htdocs/wordpress'),
    'mysql_bin' => env('MYSQL_BIN', 'C:/xampp/mysql/bin/mysql.exe'),
    'php_bin' => env('PHP_BIN', 'C:/xampp/php/php.exe'),
    'local_mode' => env('LOCAL_MODE', true),
];
